### ISSUE TITLE
Surface Release Issue on KitKat

### ISSUE THREAD

**Issue by spiderman201020** [yqritc/Android-ScalableVideoView#20]
Anyone can help me soon?

04-13 06:50:26.468 17685-17702/com.gp.edition29n E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'release' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                   at android.view.Surface.setNativeObjectLocked(Surface.java:423)
                                                                   at android.view.Surface.<init>(Surface.java:141)
                                                                   at com.yqritc.scalablevideoview.ScalableVideoView.onSurfaceTextureAvailable(ScalableVideoView.java:58)
                                                                   at android.view.TextureView.getHardwareLayer(TextureView.java:370)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15086)
                                                                   at android.view.View.getDisplayList(View.java:15132)
                                                                   at android.view.View.draw(View.java:15907)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
                                                                   at android.view.View.draw(View.java:16189)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15109)
                                                                   at android.view.View.getDisplayList(View.java:15132)
                                                                   at android.view.View.draw(View.java:15907)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15104)
                                                                   at android.view.View.getDisplayList(View.java:15132)
                                                                   at android.view.View.draw(View.java:15907)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15104)
                                                                   at android.view.View.getDisplayList(View.java:15132)
                                                                   at android.view.View.draw(View.java:15907)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
                                                                   at android.view.View.draw(View.java:16189)
                                                                   at android.widget.FrameLayout.draw(FrameLayout.java:592)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2923)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:15109)
                                                                   at android.view.View.getDisplayList(View.java:15132)
                                                                   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
                                                                   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
                                                                   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
                                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
                                                                   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5938)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by dcboy** [comment]
is same for me, how to resolve?
